### ISSUE TITLE
Better name for library :)

### ISSUE THREAD

**Issue by mjarkk** [mjarkk/yarql#6]
The currently library name is way to generic and doesn't sound really appealing

**Comment by redbar0n** [comment]
There is also a name conflict with [playlyfe/go-graphql](https://github.com/playlyfe/go-graphql), which shows up in [golang-graphql-benchmark](https://github.com/appleboy/golang-graphql-benchmark).

**Comment by redbar0n** [comment]
It's also a bit unclear if your library is an actual GraphQL server, or just a way to generate a schema, like [Nexus](https://nexusjs.org/). Since the README says:

>"Easy to implement in many web servers, see the [gin](https://github.com/mjarkk/go-graphql/blob/main/examples/gin/main.go) and [fiber](https://github.com/mjarkk/go-graphql/blob/main/examples/fiber/main.go) examples."

The description wasn't clear enough either:

> Just **a different approach to** making graphql servers in Go

**Comment by mjarkk** [comment]
At first i was like this is a GraphQL server ofc but now that i'm thinking of it i'm not sure anymore.

As stated in the readme this project does not generate code and when a Go project is referring to "generating" it usually means files are generated with code.
But that does not mean this library doesn't generates things, it analyzes your code to **generate** a map of your code layout so we can handle GraphQL queries tough this is an internal process that is not exposed to the library user.
Because of that i'm not sure if we should name it a schema generator.

On the other hand it's meant to be a sever but i don't think it actually is.
The handling of a request is dead simple and is more like a library method where you put data in and get data back and *nothing* happens in the background.
*(I say nothing but we actually re-use the same byte slices so we have less allocations but still one request doesn't have effect on another)*

I would say this is a GraphQL library meant to build a GraphQL server with. So not a generator nor a server

**Comment by redbar0n** [comment]
How would you say this library is different than [Nexus](https://nexusjs.org/)?

**Comment by redbar0n** [comment]
Name suggestion: **Allogo**

Playing on the unique feature that it has 1 memory allocation / operation.

**Comment by mjarkk** [comment]
> How would you say this library is different than [Nexus](https://nexusjs.org/)?

I don't have any experience with Nexus and neither with writing GraphQL servers in js so i can only make assumptions here.

The library gives me a very similar feel to [graphql-go/graphql](https://github.com/graphql-go/graphql)  
I personally don't like [graphql-go/graphql](https://github.com/graphql-go/graphql) and many other Go GraphQL libraries as they require you to add lots of extra code usually in the form of converters to convert your Go struct types to library understandable data.  
This is becuase in most libraries your schema type is sperate from your types in your code, this can be very nice but sometimes this means you'll 
That was the biggest reason why i made this library to get rid of most of this dumb code.

That said there are Go Libraries that generate this conversion code for you *([99designs/gqlgen](https://github.com/99designs/gqlgen))* that eliminate the annoyances i personally had with the other libraries but I'm personally not a fan of using code generators they don't feel clean and there is something nice in cloning a repo and doing a `go run .` and it runs, no more setup required.

I think you can see this library

**Comment by mjarkk** [comment]
> Name suggestion: Allogo
Playing on the unique feature that it has 1 memory allocation / operation.

Sound like a nice name tough it's not necessary a unique feature it's just well optimized :).
Still i would like to have zero allocations for basic queries.

**Comment by redbar0n** [comment]
>I don't have any experience with Nexus and neither with writing GraphQL servers in js so i can only make assumptions here. The library gives me a very similar feel to [graphql-go/graphql](https://github.com/graphql-go/graphql)
I personally don't like [graphql-go/graphql](https://github.com/graphql-go/graphql) and many other Go GraphQL libraries as they require you to add lots of extra code usually in the form of converters to convert your Go struct types to library understandable data as the library schema type is different from the go types.

Nexus actually allows you to write the types only once, in code, and then it generates the schema types based on that. So no converter is needed. The conversion is automatic through using the Nexus API. 

"GraphQL Nexus is a declarative syntax _layered on [top of]_ the graphql-js library." That seems a bit different than what [graphql-go/graphql](https://github.com/graphql-go/graphql) is, which is more a direct mirror of graphql-js (see [comparison of main.go and schema.js here](https://wehavefaces.net/learn-golang-graphql-relay-1-e59ea174a902), which also states _"graphql-go is that it has near-identical API to graphql-js"_).

**Comment by mjarkk** [comment]
Ah that makes sense, thanks for the explainer.  

I think this library is somewhat equal to to Nexus then in the sense that no conversion is needed and it does the generating of a schema for you.

Tough it's different in that it does not use an underlying library for the graphql request handeling that is handled by this library already.

**Comment by mjarkk** [comment]
Well I finally found a new name!, the project is now called YarQL!
